SELECT 
	EXTRACT('QUARTER' FROM CURRENT_TIMESTAMP);

SELECT 
	EXTRACT('CENTURY' FROM CURRENT_TIMESTAMP);

SELECT 
	EXTRACT('EPOCH' FROM CURRENT_TIMESTAMP);

SELECT 
	EXTRACT('DAY' FROM INTERVAL '2024 YEARS 2 MONTHS 11 DAYS');


